const BornToDie = [
    "Oh my heart it breaks every step that I take / but I’m hoping at the gates, / they’ll tell me that you’re mine",
    "I feel so alone on the Friday nights / can you make it feel like home, if I tell you you’re mine?",
    "Don’t make me sad, don’t make me cry / sometimes love is not enough and the road gets tough / I don’t know why",
    "The road is long, we carry on / try to have fun in the meantime",
    "Let me kiss you hard in the pouring rain / you like your girls insane",
    "This is the last time / 'cause you and I / we were born to die",
    "He loves me / with every beat of his cocaine heart",
    "Because I'm crazy, baby, / I need you to come here and save me",
    "My old man is a tough man / but he's got a soul as sweet as blood red jam",
    "My old man is a thief and I'm gonna stay and pray with him 'til the end / but I trust in the decision of the Lord to watch over us",
    "Blue jeans, white shirt / walked into the room you know you made my eyes burn",
    "I say, 'You the bestest.' / lean in for a big kiss / put his favorite perfume on",
    "I tell you all the time / heaven is a place on earth with you",
    "Diet mountain dew, baby, New York City",
    "Money is the anthem of success",
    "I'm your National Anthem",
    "He said to be cool but I'm already coolest",
    "Um, do you think you'll buy me lots of diamonds?",
    "Now my life is sweet like cinnamon / like a fucking dream I'm living in",
    "Kiss me hard before you go / summertime sadness",
    "Honey, I'm on fire, I feel it everywhere / nothing scares me anymore",
    "Think I'll miss you forever / like the stars miss the sun in the morning sky",
    "I've been out on that open road / you can be my full time daddy / white and gold",
    "Been tryin' hard not to get into trouble / but I, I've got a war in my mind",
    "I'm tired of feeling like I'm fucking crazy / I'm tired of driving 'til I see stars in my eyes / all I've got to keep myself sane, baby / so I just ride, I just ride",
    "Elvis is my daddy, Marilyn’s my mother / Jesus is my bestest friend",
    "In the land of Gods and Monsters / I was an Angel / looking to get fucked hard",
    "So I run like I'm mad to heaven's door / I don't wanna be bad / I won't cheat you no more",
    "My pussy tastes like Pepsi Cola / My eyes are wide like cherry pies",
    "Ooo ooo ooo ooh / Ooo ooo ooo ooh"
];

module.exports = BornToDie;