const NormanFuckingRockwell = [
    "You took my sadness out of context / at the Mariners Apartment Complex",
    "I ain't no candle in the wind",
    "You lose your way, just take my hand / you're lost at sea, then I'll command your boat to me again",
    "I fucked up, I know that, but Jesus / can't a girl just do the best she can?",
    "Fear fun, fear love / fresh out of fucks, forever / tryin' to be stronger for you",
    "It's me, your little Venice bitch",
    "Oh... shatter (yeah), oh... shatter (yeah, yeah), oh... shatter (yeah)",
    "(La-la-la-la-la, beautiful, beautiful, beautiful)",
    "If you weren't mine, I'd be / jealous of your love",
    "Goddamn, man-child / you fucked me so good that I almost said 'I love you'",
    "I like to see everything in neon / drink  lime green, stay up 'til dawn",
    "Dream a little dream of me",
    "Me and my girl, we got this relationship / I love her so bad, but she treats me like shit",
    "Evil, we've come to tell you that she's evil, most definitely / evil, ornery, scandalous and evil, most definitely",
    "In the car, in the car, in the backseat, I'm your baby / we go fast, we go so fast, we don’t move",
    "Lyin' on your chest in my party dress / I'm a fuckin' mess",
    "Is it safe, is it safe to just be who we are?",
    "You try to push me out, but I just find my way back in",
    "Like if you hold me without hurting me / you'll be the first who ever did",
    "Kerosene in my hands / you make me mad, on fire again",
    "You just crack another beer / and pretend that you're still here",
    "You're scared to win, scared to lose / I've heard the war was over if you really choose",
    "You hate the heat, you got the blues / changing like the weather, oh, that's so like you",
    "Those nights were on fire / we couldn't get higher / we didn't know that we had it all",
    "The culture is lit and I had a ball / I guess I'm signing off after all",
    "I miss New York and I miss the music / me and my friends‚ we miss rock 'n' roll",
    "But sometimes, girls just want to have fun / the poetry inside of me is warm like a gun",
    "I bought me a truck in the middle of the night / t'll buy me a year if I play my cards right",
    "If he's a serial killer, then what's the worst / that can happen to a girl who's already hurt?",
    "I said, 'Don't be a jerk, don't call me a taxi' / sitting in your sweatshirt, crying in the backseat, ooh",
    "Maybe I'd get less stressed if I was tested less like / all of these debutantes",
    "I've been tearing around in my fucking nightgown / 24/7 Sylvia Plath",
    "Don't ask if I'm happy, you know that I'm not / but at best, I can say I'm not sad",
    "I had 15-year dances / church basement romances, yeah, I've cried",
    "Hello, it's the most famous woman you know on the iPad / calling from beyond the grave, I just wanna say, 'Hi, Dad'",
    "Shaking my ass is the only thing that's / got this black narcissist off my back",
    "Hope is a dangerous thing for a woman like me to have / but I have it"
];

module.exports = NormanFuckingRockwell;